### ISSUE TITLE
Specifying a non-existent metrics in policy condition will cause null pointer exception during instance policy evaluation

### ISSUE THREAD

**Issue by ading1977** [TeraprocSoftware/jaguar#13]
I have the following policy condition, where `ProcessTime_mean` metrics doesn't exist in HBase:

```
      {
        "condition": {
          "componentName": "HBASE_REGIONSERVER",
          "evalMethod": "PERCENT",
          "expression": "((last(ProcessTime_mean)*last(ProcessCallTime_num_ops)-first(ProcessTime_mean)*first(ProcessCallTime_num_ops))/(last(ProcessCallTime_num_ops)-first(ProcessCallTime_num_ops)))>100",
          "threshold": ">60"
        }
      },
```

This cause null pointer exception during Jaguar policy evaluation. Here is the stack trace:

```
2016-02-22 17:31:20,113 [getThreadPoolExecutorFactoryBean-27] error:157 ERROR c.t.j.m.e.PolicyEvaluator -  [200] Unable to evaluate alert due to: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluateInstanceCondition(PolicyEvaluator.java:362)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluatePercentCondition(PolicyEvaluator.java:305)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluateNode(PolicyEvaluator.java:294)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluateNode(PolicyEvaluator.java:288)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluateGroupAlert(PolicyEvaluator.java:276)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluateGroupPolicy(PolicyEvaluator.java:165)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.evaluatePolicy(PolicyEvaluator.java:112)
        at com.teraproc.jaguar.monitor.evaluator.PolicyEvaluator.run(PolicyEvaluator.java:94)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.teraproc.jaguar.utils.AggregateUtils.last(AggregateUtils.java:48)
        ... 17 more
```

**Comment by ading1977** [comment]
Update the message.

**Comment by maweina** [comment]
Add policy with non-existent metric; jaguar works fine during policy evaluation.
